### ISSUE TITLE
Code review TODO list

### ISSUE THREAD

**Issue by ymhuang0808** [OpenISDM/VMS#71]
- [ ] Comment
  - [ ] File header comment
  - [ ] Method comment
- [x] Add folder structure and architecture description in `README.md`
  - [x] Introduce the MVC architecture
- [ ] Naming
  - [ ] Repository is inappropriate 😭 
- [ ] Endpoint versioning
